name: CI

on: [push, pull_request]

jobs:
  build-client:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.step-output.outputs.files }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "temurin"
          cache: 'gradle'

      - name: Build debug APK
        run: |
          git clone --depth=1 https://github.com/carstentrink/PipePipeExtractor.git
          git clone --depth=1 https://github.com/carstentrink/PipePipeClient.git
          cd PipePipeClient
          #./gradlew assembleDebug lintDebug --stacktrace -DskipFormatKtlint
         ./gradlew assembleRelease -DskipFormatKtlint

